### ISSUE TITLE
Include probability of 0 purchases in time range `(T, T+t]`

### ISSUE THREAD

**Issue by DylanZammit** [pymc-labs/pymc-marketing#1093] opened 2024-10-19 09:08 UTC
It is often useful to know the probability that a customer will make a purchase or not within the next `t` time periods. In some organisations "churn" is defined along the lines of

> A customer is churned if they do not make a purchase within the next `t` days/months

Currently to my knowledge, there is no available logic that can give me this information, at least not in the BetaGeo model.

Section 5.3 of [Hardie's notes](https://www.brucehardie.com/notes/039/bgnbd_derivation__2019-11-06.pdf) gives an even more general expression, which allows us to get the probability of a customer making `y` purchases within the next `t` periods.

We derived the expression for the special case when `y=0`, giving the definition of "churn" described above. The attached PDF shows the algebra, along with a brief explanation of the techniques used to avoid numerical issues.

[probability_no_deposits_derivation.pdf](https://github.com/user-attachments/files/17444473/probability_no_deposits_derivation.pdf)

**Comment by ColtAllen** [comment] 2024-10-21 12:28
This is almost a duplicate of https://github.com/pymc-labs/pymc-marketing/issues/168, but I think the expression here is a better addition as it would be conditional to each customer.

**Comment by DylanZammit** [comment] 2024-10-22 09:51
I don't think so. From what I can understand, the expression you are referring to is not conditional on the purchase history of a specific customer, unlike the expression implemented in this PR. I understand that a generalised function which accepts both the number of purchases `n` and timeframe `t` and returns the **conditional** probability is the most ideal scenario. 

If you think it is better to implement the generalised function instead of only the special case when  `n=0`, then I can spend some time trying to derive an optimised expression for this general case. Shall we go this route before making any further changes before restricting ourselves to the special case, or shall we leave generalisation as a possible future implementation?

**Comment by ColtAllen** [comment] 2024-10-24 10:29
Sorry for my delayed response; I've been traveling.

> From what I can understand, the expression you are referring to is not conditional on the purchase history of a specific customer, unlike the expression implemented in this PR. 

This is correct. That particular generalized function is the population expectation, and could also be interpreted as the purchase probability for a new, unobserved customer. However, I'm not sure if this satisfies your specific use case.

> Shall we go this route before making any further changes before restricting ourselves to the special case, or shall we leave generalisation as a possible future implementation?

After giving some more thought to this, a major achilles heel of `BetaGeoModel` is that it assumes all non-repeat (i.e., y=0) customers have a probability alive estimate of 1, and in many cases this is the most common type of customer in the dataset.  Permitting purchase probabilities in this special case is a great way to overcome this shortcoming, and a conditional generalized expression is already available for `ParetoNBDModel`.

**Closed** 2024-10-27 22:20 UTC
Labels: duplicate, enhancement, CLV
