### ISSUE TITLE
Data validation errors in MMM due to pandas index

### ISSUE THREAD

**Issue by lewi0332** [pymc-labs/pymc-marketing#346] opened 2023-08-05 16:01 UTC
Hi All, 

Just found a very small issue trying to run a sample on the latest release `0.2.0`

If I pass a pandas df that has been truncated from the original length, the `ValidateDateColumn` class throws an error telling me I have duplicate date columns.  

My test script starts with a larger data sample. I have filtered the data to within a date range. This leaves the original pandas index value.  ie... original df has 200 rows, model data now has 100 rows, but the index starts at `99`

I printed a sample in that moment of validation and see that the series has the original length of the DataFrame and an `NAT` for all empty index values.

Issue was easily solved by resetting the index of the Dataframe before starting the .fit() process. This is an outlier example as I would assume most would be loading only the data they intend to sample on.

**Comment by michaelraczycki** [comment] 2023-08-09 11:51
could you either update here a way to reproduce it, or the error you've been shown? Would it be possible for you to do the data cleaning before passing the dataset into the fit function?

**Comment by geirrlod** [comment] 2023-08-24 07:22
Hi, 

Just wanted to say that I ran into the exact same issue. If the index starts with anything else than 1 it told me that I have dublicate date columns.  But very easy fix with reseting the index (or using .loc in the first place to avoid the issue)

**Comment by PhilClarkPhD** [comment] 2023-10-10 16:22
Writing to say I had the same issue. Fixed by resetting the index.

**Comment by ricardoV94** [comment] 2023-10-18 12:58
Can someone provide a reproducible example?

**Comment by MarkusSagen** [comment] 2023-10-21 03:34
Here is a reproduced example using the example MMM notebook:

```python
import pandas as pd

# Define the data
data = {
    'date_week': ['2018-04-02', '2018-04-09', '2018-04-16', '2018-04-23', '2018-04-30'],
    'y': [3.984662, 3.762872, 4.466967, 3.864219, 4.441625],
    'x1': [0.318580, 0.112388, 0.292400, 0.071399, 0.386745],
    'x2': [0.0, 0.0, 0.812466, 0.0, 0.2164220],
}
df = pd.DataFrame(data)

df['date_week'] = pd.to_datetime(df['date_week'])

# Add 2 to the index to artificially cause the issue
df.index += 2

X = data.drop("y", axis=1)
y = data["y"]

mmm = DelayedSaturatedMMM(
    date_column="date_week",
    channel_columns=['x1', 'x2'],
    adstock_max_lag=8,
    yearly_seasonality=2,
)

mmm.fit(X=X, y=y, target_accept=0.95, chains=4, random_seed=rng)
```

Reproduces the error
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[/Users/sagenos/code/dema/mmm_test/PYMC](https://file+.vscode-resource.vscode-cdn.net/Users/sagenos/code/dema/mmm_test/PYMC) Marketing Official Notebook.ipynb Cell 37 line 1
----> [1](vscode-notebook-cell:/Users/sagenos/code/dema/mmm_test/PYMC%20Marketing%20Official%20Notebook.ipynb#X45sZmlsZQ%3D%3D?line=0) mmm.fit(X=X, y=y, target_accept=0.95, chains=4, random_seed=rng)

File [~/.pyenv/versions/3.11.2/lib/python3.11/site-packages/pymc_marketing/model_builder.py:463](https://file+.vscode-resource.vscode-cdn.net/Users/sagenos/code/dema/mmm_test/~/.pyenv/versions/3.11.2/lib/python3.11/site-packages/pymc_marketing/model_builder.py:463), in ModelBuilder.fit(self, X, y, progressbar, predictor_names, random_seed, **kwargs)
    461     y = np.zeros(X.shape[0])
    462 y_df = pd.DataFrame({self.output_var: y})
--> 463 self._generate_and_preprocess_model_data(X, y_df.values.flatten())
    464 if self.X is None or self.y is None:
    465     raise ValueError("X and y must be set before calling build_model!")

File [~/.pyenv/versions/3.11.2/lib/python3.11/site-packages/pymc_marketing/mmm/delayed_saturated_mmm.py:127](https://file+.vscode-resource.vscode-cdn.net/Users/sagenos/code/dema/mmm_test/~/.pyenv/versions/3.11.2/lib/python3.11/site-packages/pymc_marketing/mmm/delayed_saturated_mmm.py:127), in BaseDelayedSaturatedMMM._generate_and_preprocess_model_data(self, X, y)
    125 self.model_coords = coords
    126 if self.validate_data:
--> 127     self.validate("X", X_data)
    128     self.validate("y", y)
    129 self.preprocessed_data: Dict[str, Union[pd.DataFrame, pd.Series]] = {
    130     "X": self.preprocess("X", X_data),  # type: ignore
    131     "y": self.preprocess("y", y),  # type: ignore
    132 }

File [~/.pyenv/versions/3.11.2/lib/python3.11/site-packages/pymc_marketing/mmm/base.py:141](https://file+.vscode-resource.vscode-cdn.net/Users/sagenos/code/dema/mmm_test/~/.pyenv/versions/3.11.2/lib/python3.11/site-packages/pymc_marketing/mmm/base.py:141), in BaseMMM.validate(self, target, data)
    138     validation_methods = self.validation_methods[1]
    140 for method in validation_methods:
...
     42     raise ValueError(f"date_col {self.date_column} not in data")
     43 if not data[self.date_column].is_unique:
---> 44     raise ValueError(f"date_col {self.date_column} has repeated values")

ValueError: date_col date_week has repeated values
```

Have also confirmed that `resetting the index` solves the issue

**Comment by MarkusSagen** [comment] 2023-10-21 03:42
Strange thing is though, that executing the code separatly does not seem to cause this:

```python
X["date_week"].is_unique  # true
```

**Comment by MarkusSagen** [comment] 2023-10-21 04:15
Found the reason for why this happens!

If the dataframe does not have a reset index, we still add fourier components seemingly based on the dataframe index. 
This means if we artifically shifted the index, say by 2, then this is what the dataframe looks like when passed to the validation:

```python
data.index += 2

...

# We then inspect the dataframe passed to `validate_date_col()`

data.head(2)
"""
   date_week        x1   x2  sin_order_1  cos_order_1  sin_order_2  cos_order_2  
2 2018-04-02  0.318580  0.0     0.968251    -0.249981    -0.484089   -0.875019  
3 2018-04-09  0.112388  0.0     0.931210    -0.364483    -0.678820    -0.734304
"""

data.tail(2)   
"""
     date_week  x1  x2  sin_order_1  cos_order_1  sin_order_2  cos_order_2
0       NaT NaN NaN     0.999930    -0.011826    -0.023651    -0.999720
1       NaT NaN NaN     0.991269    -0.131859    -0.261414    -0.965227
"""
```

**Comment by MarkusSagen** [comment] 2023-10-21 04:39
@ricardoV94 Now there's a PR up solving this issue

**Comment by PhilClarkPhD** [comment] 2023-11-09 16:54
Strangely I am now getting this error even when I reset my index and ensure it is continuous from 0-n and matches for X and y. Any idea why?

**Comment by PhilClarkPhD** [comment] 2023-11-09 17:54
> Strangely I am now getting this error even when I reset my index and ensure it is continuous from 0-n and matches for X and y. Any idea why?

Solved - had accidentally included my date column in the channel_columns as well as specified it as the date_column here:

`mmm = DelayedSaturatedMMM(
    model_config = my_model_config,
    sampler_config = sampler_config,
    date_column='date',
    channel_columns=paid_media_spends,
    control_columns=context_vars,
    adstock_max_lag=4,  
    yearly_seasonality=None,
)`

**Comment by wd60622** [comment] 2024-07-09 09:26
Ran the reproducible on latest main branch with success. 

Will close issue. 
Feel free to open if needed

**Closed by wd60622** 2024-07-09 09:26 UTC
Labels: bug, good first issue, MMM
