### ISSUE TITLE
Streamlit app down? 

### ISSUE THREAD

**Issue by wd60622** [pymc-labs/pymc-marketing#701] opened 2024-05-26 14:19 UTC
Is this the correct link? https://pymc-marketing-app.streamlit.app/
It is down for me

Are there logs for this application?

CC: @louismagowan 

![app-down](https://github.com/pymc-labs/pymc-marketing/assets/57733339/2f3c374d-6430-46b7-bfaf-1502bfe40115)

**Comment by louismagowan** [comment] 2024-05-26 17:19
I am travelling atm but will check this this evening. I think I know what the issue is though.

Because I don't have admin permissions on pymc-marketing, I had to deploy the app from my forked version. Now that the branch has been merged I guess it's been deleted so Streamlit points to nothing.

I'll double check tonight, but I think that's the problem. Tbh it's probably for the best, the app should be deployed directly from main branch in pymc-marketing directly. Will mean it's stable and we can actually merge into it with proper Git workflows in future.

Would an admin be able to liaise with me on this? The deployment takes honestly a few mins to set up and I'm happy to hop on a call about it, but it would need to be done by an admin ☺️

**Comment by louismagowan** [comment] 2024-05-26 19:20
Ok it actually wasn't the issue I thought it was haha. I rebooted it to try and see if the logs would reproduce the issue, but it seems to be working fine now. Perhaps this was just a problem with Streamlit servers?

In any case, I think it's good this was flagged - I still think someone with admin rights on pymc-marketing should recreate the deployment from main, rather than using my forked version. ☺️ 

Lemme know if it's still not working for you Will, but it LGTM

**Comment by wd60622** [comment] 2024-05-27 00:39
> In any case, I think it's good this was flagged - I still think someone with admin rights on pymc-marketing should recreate the deployment from main, rather than using my forked version. ☺️

Sounds good. I will create an issue. Maybe you can walk us through or take it. In my mind, if there is an action controlling it, a specific user won't need admin rights

**Closed** 2024-05-29 09:04 UTC
Labels: MMM
